### Регистрация нового пользователя
POST http://localhost:8090/api/v1/auth/sign-up
Content-Type: application/json

{
  "name": "qw",
  "email": "qw1@wqw",
  "password": "123"
}

### Авторизация пользователя
POST http://localhost:8090/api/v1/auth/sign-in
Content-Type: application/json

{
  "email": "qw1@wqw",
  "password": "123"
}