###Запрос сброса пароля
POST http://localhost:8090/api/v1/auth/forgot
Content-Type: application/json

{
  "login": "qw1@wqw"
}

###Подтверждение сброса
POST http://localhost:8090/api/v1/auth/reset
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk1ODAzNDgsImlhdCI6MTc0OTU3OTc0OCwidXNlcm5hbWUiOiJxdzFAd3F3In0.5PVnkqBkB-8cYhIQ29SQiSeP46l2ANJFnpba_0mUEDY",
  "new_password": "123456"
}