### Регистрация нового пользователя
GET http://localhost:8090/api/v1/user/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDU5OTUyMDMsImlhdCI6MTc0NTk1MjAwMywidXNlcl9pZCI6MywidXNlcm5hbWUiOiJxdyJ9.5TddqyildVklYcj_goq-DRK3sG8twLoFAO2Q8sx1eIg
